const { hairlineWidth } = require('nativewind/theme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          background: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        /* Color Palette */
        grey: {
          50: 'hsl(var(--grey-50))',
          100: 'hsl(var(--grey-100))',
          200: 'hsl(var(--grey-200))',
          300: 'hsl(var(--grey-300))',
          400: 'hsl(var(--grey-400))',
          500: 'hsl(var(--grey-500))',
          600: 'hsl(var(--grey-600))',
          700: 'hsl(var(--grey-700))',
          800: 'hsl(var(--grey-800))',
          900: 'hsl(var(--grey-900))',
          950: 'hsl(var(--grey-950))',
        },
        red: {
          50: 'hsl(var(--red-50))',
          100: 'hsl(var(--red-100))',
          200: 'hsl(var(--red-200))',
          300: 'hsl(var(--red-300))',
          400: 'hsl(var(--red-400))',
          500: 'hsl(var(--red-500))',
          600: 'hsl(var(--red-600))',
          700: 'hsl(var(--red-700))',
          800: 'hsl(var(--red-800))',
          900: 'hsl(var(--red-900))',
          950: 'hsl(var(--red-950))',
        },
        orange: {
          50: 'hsl(var(--orange-50))',
          100: 'hsl(var(--orange-100))',
          200: 'hsl(var(--orange-200))',
          300: 'hsl(var(--orange-300))',
          400: 'hsl(var(--orange-400))',
          500: 'hsl(var(--orange-500))',
          600: 'hsl(var(--orange-600))',
          700: 'hsl(var(--orange-700))',
          800: 'hsl(var(--orange-800))',
          900: 'hsl(var(--orange-900))',
          950: 'hsl(var(--orange-950))',
        },
        yellow: {
          50: 'hsl(var(--yellow-50))',
          100: 'hsl(var(--yellow-100))',
          200: 'hsl(var(--yellow-200))',
          300: 'hsl(var(--yellow-300))',
          400: 'hsl(var(--yellow-400))',
          500: 'hsl(var(--yellow-500))',
          600: 'hsl(var(--yellow-600))',
          700: 'hsl(var(--yellow-700))',
          800: 'hsl(var(--yellow-800))',
          900: 'hsl(var(--yellow-900))',
          950: 'hsl(var(--yellow-950))',
        },
        'light-green': {
          50: 'hsl(var(--light-green-50))',
          100: 'hsl(var(--light-green-100))',
          200: 'hsl(var(--light-green-200))',
          300: 'hsl(var(--light-green-300))',
          400: 'hsl(var(--light-green-400))',
          500: 'hsl(var(--light-green-500))',
          600: 'hsl(var(--light-green-600))',
          700: 'hsl(var(--light-green-700))',
          800: 'hsl(var(--light-green-800))',
          900: 'hsl(var(--light-green-900))',
          950: 'hsl(var(--light-green-950))',
        },
        green: {
          50: 'hsl(var(--green-50))',
          100: 'hsl(var(--green-100))',
          200: 'hsl(var(--green-200))',
          300: 'hsl(var(--green-300))',
          400: 'hsl(var(--green-400))',
          500: 'hsl(var(--green-500))',
          600: 'hsl(var(--green-600))',
          700: 'hsl(var(--green-700))',
          800: 'hsl(var(--green-800))',
          900: 'hsl(var(--green-900))',
          950: 'hsl(var(--green-950))',
        },
        teal: {
          50: 'hsl(var(--teal-50))',
          100: 'hsl(var(--teal-100))',
          200: 'hsl(var(--teal-200))',
          300: 'hsl(var(--teal-300))',
          400: 'hsl(var(--teal-400))',
          500: 'hsl(var(--teal-500))',
          600: 'hsl(var(--teal-600))',
          700: 'hsl(var(--teal-700))',
          800: 'hsl(var(--teal-800))',
          900: 'hsl(var(--teal-900))',
          950: 'hsl(var(--teal-950))',
        },
        cyan: {
          50: 'hsl(var(--cyan-50))',
          100: 'hsl(var(--cyan-100))',
          200: 'hsl(var(--cyan-200))',
          300: 'hsl(var(--cyan-300))',
          400: 'hsl(var(--cyan-400))',
          500: 'hsl(var(--cyan-500))',
          600: 'hsl(var(--cyan-600))',
          700: 'hsl(var(--cyan-700))',
          800: 'hsl(var(--cyan-800))',
          900: 'hsl(var(--cyan-900))',
          950: 'hsl(var(--cyan-950))',
        },
        'light-blue': {
          50: 'hsl(var(--light-blue-50))',
          100: 'hsl(var(--light-blue-100))',
          200: 'hsl(var(--light-blue-200))',
          300: 'hsl(var(--light-blue-300))',
          400: 'hsl(var(--light-blue-400))',
          500: 'hsl(var(--light-blue-500))',
          600: 'hsl(var(--light-blue-600))',
          700: 'hsl(var(--light-blue-700))',
          800: 'hsl(var(--light-blue-800))',
          900: 'hsl(var(--light-blue-900))',
          950: 'hsl(var(--light-blue-950))',
        },
        blue: {
          50: 'hsl(var(--blue-50))',
          100: 'hsl(var(--blue-100))',
          200: 'hsl(var(--blue-200))',
          300: 'hsl(var(--blue-300))',
          400: 'hsl(var(--blue-400))',
          500: 'hsl(var(--blue-500))',
          600: 'hsl(var(--blue-600))',
          700: 'hsl(var(--blue-700))',
          800: 'hsl(var(--blue-800))',
          900: 'hsl(var(--blue-900))',
          950: 'hsl(var(--blue-950))',
        },
        purple: {
          50: 'hsl(var(--purple-50))',
          100: 'hsl(var(--purple-100))',
          200: 'hsl(var(--purple-200))',
          300: 'hsl(var(--purple-300))',
          400: 'hsl(var(--purple-400))',
          500: 'hsl(var(--purple-500))',
          600: 'hsl(var(--purple-600))',
          700: 'hsl(var(--purple-700))',
          800: 'hsl(var(--purple-800))',
          900: 'hsl(var(--purple-900))',
          950: 'hsl(var(--purple-950))',
        },
        'light-purple': {
          50: 'hsl(var(--light-purple-50))',
          100: 'hsl(var(--light-purple-100))',
          200: 'hsl(var(--light-purple-200))',
          300: 'hsl(var(--light-purple-300))',
          400: 'hsl(var(--light-purple-400))',
          500: 'hsl(var(--light-purple-500))',
          600: 'hsl(var(--light-purple-600))',
          700: 'hsl(var(--light-purple-700))',
          800: 'hsl(var(--light-purple-800))',
          900: 'hsl(var(--light-purple-900))',
          950: 'hsl(var(--light-purple-950))',
        },
        violet: {
          50: 'hsl(var(--violet-50))',
          100: 'hsl(var(--violet-100))',
          200: 'hsl(var(--violet-200))',
          300: 'hsl(var(--violet-300))',
          400: 'hsl(var(--violet-400))',
          500: 'hsl(var(--violet-500))',
          600: 'hsl(var(--violet-600))',
          700: 'hsl(var(--violet-700))',
          800: 'hsl(var(--violet-800))',
          900: 'hsl(var(--violet-900))',
          950: 'hsl(var(--violet-950))',
        },
        magenta: {
          50: 'hsl(var(--magenta-50))',
          100: 'hsl(var(--magenta-100))',
          200: 'hsl(var(--magenta-200))',
          300: 'hsl(var(--magenta-300))',
          400: 'hsl(var(--magenta-400))',
          500: 'hsl(var(--magenta-500))',
          600: 'hsl(var(--magenta-600))',
          700: 'hsl(var(--magenta-700))',
          800: 'hsl(var(--magenta-800))',
          900: 'hsl(var(--magenta-900))',
          950: 'hsl(var(--magenta-950))',
        },
        pink: {
          50: 'hsl(var(--pink-50))',
          100: 'hsl(var(--pink-100))',
          200: 'hsl(var(--pink-200))',
          300: 'hsl(var(--pink-300))',
          400: 'hsl(var(--pink-400))',
          500: 'hsl(var(--pink-500))',
          600: 'hsl(var(--pink-600))',
          700: 'hsl(var(--pink-700))',
          800: 'hsl(var(--pink-800))',
          900: 'hsl(var(--pink-900))',
          950: 'hsl(var(--pink-950))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      borderWidth: {
        hairline: hairlineWidth(),
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  future: {
    hoverOnlyWhenSupported: true,
  },
  plugins: [require('tailwindcss-animate')],
};
